services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5


  django:
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8000/api/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file: .env

  nginx:
    container_name: nginx
    env_file: .env
    depends_on:
      django:
        condition: service_healthy
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
    networks:
      - main
    volumes:
      - /var/www/html
      - ./ssl/certs:/etc/ssl/nginx/certs
      - ./ssl/private:/etc/ssl/nginx/private
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ./vault/vault-config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file
      - ./ssl/certs:/etc/vault/certs
      - ./ssl/private:/etc/vault/private
    cap_add:
      - IPC_LOCK
    command: server
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    
  vault-init:
    image: hashicorp/vault:1.16
    container_name: vault-init
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN}
    volumes:
      - ./vault/vault-root-token:/vault/file/vault-root-token
      - ./vault/vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-data:/vault/file/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault

networks:
  main:
    name: main
    driver: bridge

volumes:
  vault-data:
