services:
  db:
    container_name: db
    env_file:
      - .env
    image: postgres
    restart: always
    networks:
      - main
    volumes:
      - ./volume/db-data:/var/lib/postgresql/data
      - ./volume/logs-data/postgres:/var/log/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5

  django:
    container_name: django
    depends_on:
      vault:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./images/backend/Dockerfile
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    restart: always
    volumes:
      - ./volume/vault-data:/vault/file
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
      - ./volume/logs-data/django:/var/log/django
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8000/api/user/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
    build:
      context: ./images/build
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
    networks:
      - main
    volumes:
      - /var/www/html
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
      - ./volume/vault-data:/vault/file
      - ./volume/logs-data/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      django:
        condition: service_healthy
      vault:
        condition: service_healthy

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_CACERT=${VAULT_CACERT}
    ports:
      - 8200:8200
    restart: always
    networks:
      - main
    volumes:
      - ./images/vault/vault-config.hcl:/vault/config/config.hcl
      - ./volume/vault-data:/vault/file/
      - ./images/vault/start-vault.sh:/./start-vault.sh
      - ./ssl/certs:/etc/vault/certs
      - ./ssl/private:/etc/vault/private
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c", "/start-vault.sh"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  vault-init:
    image: hashicorp/vault:1.16
    container_name: vault-init
    restart: on-failure
    networks:
      - main
    env_file: .env
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN}
      - VAULT_CACERT=${VAULT_CACERT}
    volumes:
      - ./images/vault/vault-init.sh:/usr/local/bin/vault-init.sh
      - ./volume/vault-data:/vault/file/
      - ./ssl/certs:/etc/vault/certs
      - ./ssl/private:/etc/vault/private
      - ./volume/logs-data/vault:/var/log/vault
    command: /usr/local/bin/vault-init.sh
    depends_on:
      - vault

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - main
    volumes:
      - ./volume/logs-data/redis:/var/log/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    build:
      context: ./images/ELK/
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - main
    volumes:
      - ./volume/logs-data:/var/log/elasticsearch
      - ./volume/es-snapshots:/usr/share/elasticsearch/volume/snapshots
      - ./ssl/:/usr/share/elasticsearch/config/certs/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTIC_HOST}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${KIBANA_SSL_PATH}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - main
    volumes:
      - ./volume/es-certif:/usr/share/kibana/config/certs
      - ./volume/logs-data:/var/log/kibana

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTIC_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - "5044:5044"
    networks:
      - main
    volumes:
      - ./images/ELK/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./volume/es-certif:/usr/share/logstash/config/certs
      - ./volume/logs-data:/usr/share/logstash/logs

networks:
  main:
    name: main
    driver: bridge

volumes:
  es-snapshots:
  es-certif:
  vault-data:
  logs-data:
  db-data:
