services:
  db:
    container_name: db
    env_file:
      - .env
    image: postgres
    restart: always
    networks:
      - main
    volumes:
      - ./volume/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5

  django:
    container_name: django
    depends_on:
      vault:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./images/backend/Dockerfile
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    restart: always
    volumes:
      - ./volume/vault-data:/vault/file
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
      - ./volume/logs-data:/var/log/django
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8000/api/user/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
    build:
      context: ./images/build
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: always
    networks:
      - main
    volumes:
      - /var/www/html
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
      - ./volume/vault-data:/vault/file
      - ./volume/logs-data:/var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      django:
        condition: service_healthy
      vault:
        condition: service_healthy

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_CACERT=${VAULT_CACERT}
    ports:
      - 8200:8200
    restart: always
    networks:
      - main
    volumes:
      - ./images/vault/vault-config.hcl:/vault/config/config.hcl
      - ./volume/vault-data:/vault/file/
      - ./images/vault/start-vault.sh:/./start-vault.sh
      - ./ssl/certs:/etc/vault/certs
      - ./ssl/private:/etc/vault/private
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c", "/start-vault.sh"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  vault-init:
    image: hashicorp/vault:1.16
    container_name: vault-init
    restart: on-failure
    networks:
      - main
    env_file: .env
    environment:
      - VAULT_ADDR=${VAULT_INIT_ADDR}
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN}
      - VAULT_CACERT=${VAULT_CACERT}
    volumes:
      - ./images/vault/vault-init.sh:/usr/local/bin/vault-init.sh
      - ./volume/vault-data:/vault/file/
      - ./ssl/certs:/etc/vault/certs
      - ./ssl/private:/etc/vault/private
    command: /usr/local/bin/vault-init.sh
    depends_on:
      - vault

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - main
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  elasticsearch:
    build:
      context: ./images/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    networks:
      - main
    restart: unless-stopped
    volumes:
      - ./images/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./volume/elasticsearch-data:/usr/share/elasticsearch/data:Z
      - ./ssl/certs:/usr/share/elasticsearch/config/certs:ro,z
      - ./ssl/private:/usr/share/elasticsearch/config/private:ro,z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node


  logstash:
    build:
      context: ./images/logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    networks:
      - main
    restart: unless-stopped
    volumes:
      - ./images/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./ssl/certs/ca.crt:/usr/share/logstash/config/ca.crt:ro,z
    ports:
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    depends_on:
      - elasticsearch
  
  kibana:
    build:
      context: ./images/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./images/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      - ./ssl/certs/ca.crt:/usr/share/kibana/config/kibana.crt:ro,Z
      - ./ssl/private/private.key:/usr/share/kibana/config/kibana.key:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - main
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  main:
    name: main
    driver: bridge

volumes:
  vault-data:
  postgres-data:
  elasticsearch-data:
  logs-data:
  db_data: