services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 3
      timeout: 5s
  
  django:
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/api/ || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 3
    env_file: .env
  
  nginx:
    container_name: nginx
    env_file: .env
    depends_on:
      django:
        condition: service_healthy
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        - NGINX_PROTOCOL=https
    ports:
      - '8000:8000'
    restart: always
    networks:
      - main
    volumes:
      - /var/www/html
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:8000/ || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 3

  vault:
    container_name: vault
    build:
      context: ./vault
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8200:8200"
    networks:
      - main



networks:
  main:
    name: main
    driver: bridge