input {
  # Nginx Access Logs
  file {
    path => "/var/log/nginx/access.log"
    start_position => "beginning"
    type => "nginx-access"
  }

  # Nginx Error Logs
  file {
    path => "/var/log/nginx/error.log"
    start_position => "beginning"
    type => "nginx-error"
  }

  # Django Logs
  file {
    path => "/var/log/django/debug.log"
    start_position => "beginning"
    type => "django"
  }
}

filter {
  # Filter for Nginx Access Logs
  if [type] == "nginx-access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
  }

  # Filter for Nginx Error Logs
  if [type] == "nginx-error" {
    grok {
      match => { "message" => "%{NGINX_ERROR}" }
    }
    date {
      match => [ "timestamp" , "YYYY/MM/dd HH:mm:ss" ]
      target => "@timestamp"
    }
  }

  # Filter for Django Logs
  if [type] == "django" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{type}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
		ssl => true
		cacert => "config/ca.crt"
	}
}