# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
