input {
  file {
    path => "/usr/share/logstash/logs/django/*.log"
    start_position => "beginning"
    sincedb_clean_after => "1 week"
    type => "django"
  }
  
  file {
    path => "/usr/share/logstash/logs/nginx/*.log"
    start_position => "beginning"
    sincedb_clean_after => "1 week"
    type => "nginx"
  }
  
  file {
    path => "/usr/share/logstash/logs/redis/*.log"
    start_position => "beginning"
    sincedb_clean_after => "1 week"
    type => "redis"
  }
  
  file {
    path => "/usr/share/logstash/logs/postgres/*.log"
    start_position => "beginning"
    sincedb_clean_after => "1 week"
    type => "postgres"
  }

    file {
    path => "/usr/share/logstash/logs/vault/*.log" 
    start_position => "beginning"
    sincedb_clean_after => "1 week"
    type => "vault"
  }
}

filter {
  if [path] =~ "/usr/share/logstash/logs/nginx/.*\.log" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    mutate {
      remove_field => ["path", "host", "offset"]
    }
  }
  
  else if [path] =~ "/usr/share/logstash/logs/django/.*\.log" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    mutate {
      remove_field => ["path", "host", "offset"]
    }
  }
  
  else if [path] =~ "/usr/share/logstash/logs/redis/.*\.log" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    mutate {
      remove_field => ["path", "host", "offset"]
    }
  }
  
  else if [path] =~ "/usr/share/logstash/logs/postgres/.*\.log" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{LOGLEVEL:level}\] %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    mutate {
      remove_field => ["path", "host", "offset"]
    }
  }

  else if [type] == "vault" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    mutate {
      remove_field => ["path", "host", "offset"]
    }
  }

}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS}"]
    cacert => "/usr/share/logstash/config/certs/ca-certificates.pem"
    ssl => true
	index => "logs-%{+YYYY.MM.dd}"
	user => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    # If you're using client authentication, you can also specify:
    # keystore => "/usr/share/logstash/config/certs/elastic-certificates.p12"
    # keystore_password => "your_password"
  }
}
